"""Add native lexical contracts, versioned editions and durable task processing.

Revision ID: 20260912_20
Revises: 20260828_19

DDL is frozen here. Production upgrade requires verified migration authorization.
"""

import sqlalchemy as sa

from alembic import op

revision = "20260912_20"
down_revision = "20260828_19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    from multilang.services.native_migration import require_schema_authorization

    require_schema_authorization(op.get_context().config, op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_versions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("signature_sha256", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_audio_versions_signature_sha256"),
        "audio_versions",
        ["signature_sha256"],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("before_sha256", sa.String(length=64), nullable=True),
        sa.Column("after_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("language", "kind", "namespace", "owner_id", "version"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_dataset_versions_language"), "dataset_versions", ["language"], unique=False
    )
    op.create_table(
        "domain_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_domain_events_delivered_at"), "domain_events", ["delivered_at"], unique=False
    )
    op.create_index(
        op.f("ix_domain_events_event_type"), "domain_events", ["event_type"], unique=False
    )
    op.create_table(
        "language_profiles",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("language", "version"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_language_profiles_language"), "language_profiles", ["language"], unique=False
    )
    op.create_table(
        "lexical_identities",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("normalized_lemma", sa.String(length=512), nullable=False),
        sa.Column("part_of_speech", sa.String(length=64), nullable=False),
        sa.Column("sense_id", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        "ix_native_lexical_lookup",
        "lexical_identities",
        ["language", "normalized_lemma"],
        unique=False,
    )
    op.create_table(
        "migration_journal",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("target_sha256", sa.String(length=64), nullable=False),
        sa.Column("backup_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_table(
        "native_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_expires_at", sa.Float(), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("result_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','cancelled')",
            name="ck_native_task_status",
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND max_attempts >= 1 AND attempts <= max_attempts",
            name="ck_native_task_attempts",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "idempotency_key", name="uq_native_task_owner_key"),
        info={"native": True},
    )
    op.create_index(
        "ix_native_tasks_claim",
        "native_tasks",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(op.f("ix_native_tasks_owner_id"), "native_tasks", ["owner_id"], unique=False)
    op.create_table(
        "user_state",
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("owner_id", "key"),
        info={"native": True},
    )
    op.create_table(
        "content_versions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("identity_id", sa.String(length=128), nullable=False),
        sa.Column("namespace", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("edition_id", sa.String(length=128), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lexical_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        "ix_content_owner_identity", "content_versions", ["owner_id", "identity_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_versions_edition_id"), "content_versions", ["edition_id"], unique=False
    )
    op.create_table(
        "dataset_heads",
        sa.Column("channel", sa.String(length=255), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("channel"),
        info={"native": True},
    )
    op.create_table(
        "dataset_memberships",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("identity_id", sa.String(length=128), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("identity_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lexical_identities.id"],
        ),
        sa.PrimaryKeyConstraint("dataset_id", "identity_id"),
        sa.UniqueConstraint("dataset_id", "rank"),
        info={"native": True},
    )
    op.create_table(
        "deck_editions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("bundle_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_deck_editions_dataset_id"), "deck_editions", ["dataset_id"], unique=False
    )
    op.create_table(
        "legacy_identity_aliases",
        sa.Column("legacy_guid", sa.String(length=128), nullable=False),
        sa.Column("identity_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lexical_identities.id"],
        ),
        sa.PrimaryKeyConstraint("legacy_guid"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_legacy_identity_aliases_identity_id"),
        "legacy_identity_aliases",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "lexical_identity_revisions",
        sa.Column("identity_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lexical_identities.id"],
        ),
        sa.PrimaryKeyConstraint("identity_id", "revision"),
        info={"native": True},
    )
    op.create_table(
        "surface_forms",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("identity_id", sa.String(length=128), nullable=False),
        sa.Column("analysis_id", sa.String(length=128), nullable=False),
        sa.Column("normalized_text", sa.String(length=512), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["lexical_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"native": True},
    )
    op.create_index(
        op.f("ix_surface_forms_identity_id"), "surface_forms", ["identity_id"], unique=False
    )
    op.create_index(
        op.f("ix_surface_forms_normalized_text"), "surface_forms", ["normalized_text"], unique=False
    )
    op.create_table(
        "dataset_form_memberships",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("form_id", sa.String(length=128), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["surface_forms.id"],
        ),
        sa.PrimaryKeyConstraint("dataset_id", "form_id"),
        info={"native": True},
    )
    op.create_table(
        "surface_form_revisions",
        sa.Column("form_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["surface_forms.id"],
        ),
        sa.PrimaryKeyConstraint("form_id", "revision"),
        info={"native": True},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    from multilang.services.native_migration import require_schema_authorization

    require_schema_authorization(op.get_context().config, op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surface_form_revisions")
    op.drop_table("dataset_form_memberships")
    op.drop_index(op.f("ix_surface_forms_normalized_text"), table_name="surface_forms")
    op.drop_index(op.f("ix_surface_forms_identity_id"), table_name="surface_forms")
    op.drop_table("surface_forms")
    op.drop_table("lexical_identity_revisions")
    op.drop_index(
        op.f("ix_legacy_identity_aliases_identity_id"), table_name="legacy_identity_aliases"
    )
    op.drop_table("legacy_identity_aliases")
    op.drop_index(op.f("ix_deck_editions_dataset_id"), table_name="deck_editions")
    op.drop_table("deck_editions")
    op.drop_table("dataset_memberships")
    op.drop_table("dataset_heads")
    op.drop_index(op.f("ix_content_versions_edition_id"), table_name="content_versions")
    op.drop_index("ix_content_owner_identity", table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_table("user_state")
    op.drop_index(op.f("ix_native_tasks_owner_id"), table_name="native_tasks")
    op.drop_index("ix_native_tasks_claim", table_name="native_tasks")
    op.drop_table("native_tasks")
    op.drop_table("migration_journal")
    op.drop_index("ix_native_lexical_lookup", table_name="lexical_identities")
    op.drop_table("lexical_identities")
    op.drop_index(op.f("ix_language_profiles_language"), table_name="language_profiles")
    op.drop_table("language_profiles")
    op.drop_index(op.f("ix_domain_events_event_type"), table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_delivered_at"), table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_index(op.f("ix_dataset_versions_language"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_audio_versions_signature_sha256"), table_name="audio_versions")
    op.drop_table("audio_versions")
    # ### end Alembic commands ###
